package gowsdl

var serverHeaderTmpl = `
// Code generated by gowsdl DO NOT EDIT.

package {{.}}

import (
	"io"
	"fmt"
	"errors"
	"strings"
	"encoding/xml"
	"net/http"

	"github.com/beevik/etree"
	dsig "github.com/russellhaering/goxmldsig"
	"github.com/vxfiber/gowsdl/soap"

	{{/*range .Imports*/}}
		{{/*.*/}}
	{{/*end*/}}
)

`
