package gowsdl

var serverHeaderTmpl = `
// Code generated by gowsdl DO NOT EDIT.

package {{.}}

import (
	"fmt"
	"errors"
	"strings"
	"encoding/xml"
	"net/http"

	{{/*range .Imports*/}}
		{{/*.*/}}
	{{/*end*/}}
)

`
